/**
 * Universal AI Provider Interface.
 *
 * Decouples the Agent Harness from any specific vendor (Google, OpenAI, Anthropic, Ollama, etc.).
 * Any LLM that supports function/tool calling can be used interchangeably.
 */

import type { ToolSchema } from "./types.js";

/** Standard function call requested by an LLM. */
export interface FunctionCallRequest {
  id?: string;
  name: string;
  args: Record<string, unknown>;
}

/** Standard function execution response sent back to the LLM. */
export interface FunctionExecutionResponse {
  id?: string;
  name: string;
  response: Record<string, unknown>;
}

/** Token usage statistics for a turn. */
export interface TokenUsage {
  promptTokens?: number;
  completionTokens?: number;
  totalTokens?: number;
  embeddingTokens?: number;
  embeddingModel?: string;
}

/** Standard LLM turn result. */
export interface LLMTurnResult {
  /** Text generated by the model (if any). */
  text: string | null;
  /** Function calls requested by the model (if any). */
  functionCalls: FunctionCallRequest[];
  /** Finish reason from provider (e.g. 'stop', 'tool_calls', 'length'). */
  finishReason?: string;
  /** Token usage statistics (if provided by LLM). */
  usage?: TokenUsage;
}

/** Supported AI Providers */
export type ProviderType =
  | "gemini"
  | "openai"
  | "anthropic"
  | "ollama"
  | "lmstudio"
  | "groq"
  | "deepseek"
  | "openrouter"
  | "custom";

/** Configuration for creating an AI Provider instance. */
export interface ProviderConfig {
  provider?: ProviderType;
  model?: string;
  apiKey?: string;
  baseUrl?: string;
  embeddingModel?: string;
  embeddingProvider?: ProviderType;
  systemPrompt?: string;
  temperature?: number;
}

/** The Universal AI Provider contract. */
export interface AIProvider {
  /** Unique provider identifier (e.g., 'gemini', 'openai', 'anthropic', 'ollama'). */
  readonly providerType: ProviderType;
  /** Active model identifier (e.g., 'gemini-3.5-flash-lite', 'gpt-4o', 'claude-3-7-sonnet'). */
  readonly model: string;
  /** Active embedding model identifier. */
  readonly embeddingModel: string;

  /** Initialize a stateful multi-turn chat session with tools and system prompt. */
  createChat(systemPrompt: string, tools: ToolSchema[]): void;

  /**
   * Rehydrate an existing conversation into the provider's internal history
   * without making any API calls (used to restore past session context).
   * `messages` alternate between user and model turns in chronological order.
   */
  loadConversationHistory(
    messages: ReadonlyArray<{ role: "user" | "model"; content: string }>
  ): void;

  /** Send a user prompt (or augmented prompt) and receive model turn response. */
  sendMessage(userMessage: string): Promise<LLMTurnResult>;

  /** Send tool execution responses back to the model for the next reasoning cycle. */
  sendFunctionResponses(
    responses: FunctionExecutionResponse[]
  ): Promise<LLMTurnResult>;

  /** Generate a 32-bit floating point embedding vector for text. */
  embed(text: string): Promise<Float32Array>;

  /** Batch generate embedding vectors. */
  embedBatch(texts: string[]): Promise<Float32Array[]>;
}
